# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloseWiki < Formula
  desc "Agentic repo-to-wiki — scan any codebase into a structured knowledge base"
  homepage "https://github.com/unrealandychan/close-wiki"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v0.9.1/close-wiki_darwin_amd64.tar.gz"
      sha256 "b9243f07801a7a6df79ebbed062c346a00f2f28705ac2a71d8518ad1eeef5763"

      define_method(:install) do
        bin.install "close-wiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v0.9.1/close-wiki_darwin_arm64.tar.gz"
      sha256 "b9c6194af5e8ee95d9fc8cbd88edba8507e413750024aac86fae2c7863881233"

      define_method(:install) do
        bin.install "close-wiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v0.9.1/close-wiki_linux_amd64.tar.gz"
      sha256 "727037ce7acc57c741fdbba575dac342e76b498f952a0249b81368442d0ac87b"
      define_method(:install) do
        bin.install "close-wiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v0.9.1/close-wiki_linux_arm64.tar.gz"
      sha256 "03f57fef16d9dc2d719ca40a2078de9b804ed9e3b9dacae07c2b61e0a63da01c"
      define_method(:install) do
        bin.install "close-wiki"
      end
    end
  end

  test do
    system "#{bin}/close-wiki", "--version"
  end
end
