# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloseWiki < Formula
  desc "Agentic repo-to-wiki — scan any codebase into a structured knowledge base"
  homepage "https://github.com/unrealandychan/close-wiki"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.9.0/close-wiki_darwin_amd64.tar.gz"
      sha256 "af525892c83f2e2e5bb343f4a772823da4667c304ab45a4268345efef3e5c386"

      define_method(:install) do
        bin.install "close-wiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.9.0/close-wiki_darwin_arm64.tar.gz"
      sha256 "c5a409db536d0c44fde5b3a730689a1362be2481360d11b5282300854a08d26d"

      define_method(:install) do
        bin.install "close-wiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.9.0/close-wiki_linux_amd64.tar.gz"
      sha256 "8ba8b6c86732f35f55feeecc786ceafb4576700f5d8a16888e51f76408e26be3"
      define_method(:install) do
        bin.install "close-wiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.9.0/close-wiki_linux_arm64.tar.gz"
      sha256 "e7227b20c81b59fbbc378e3c57db3d76d1f6641af2bda0c2cd1366a665efceea"
      define_method(:install) do
        bin.install "close-wiki"
      end
    end
  end

  test do
    system "#{bin}/close-wiki", "--version"
  end
end
