# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloseWiki < Formula
  desc "Agentic repo-to-wiki — scan any codebase into a structured knowledge base"
  homepage "https://github.com/unrealandychan/close-wiki"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v0.9.0/close-wiki_darwin_amd64.tar.gz"
      sha256 "b3c2761fd79ea957b82237df89d178c2a0e6ce5eee201b2372ef8082c8cc83eb"

      define_method(:install) do
        bin.install "close-wiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v0.9.0/close-wiki_darwin_arm64.tar.gz"
      sha256 "48dfe2373a51d3974d72faebb768eeace9871b5aa4f301db63d976dd16153ed8"

      define_method(:install) do
        bin.install "close-wiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v0.9.0/close-wiki_linux_amd64.tar.gz"
      sha256 "390118c9a6b54b2f0088cc29687a7be4d293c4362fa245353fcdda8d7724d581"
      define_method(:install) do
        bin.install "close-wiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v0.9.0/close-wiki_linux_arm64.tar.gz"
      sha256 "471ea708f94991c20cd1c48067d0d6756c207ba19fad4c1b44f692e27f0684af"
      define_method(:install) do
        bin.install "close-wiki"
      end
    end
  end

  test do
    system "#{bin}/close-wiki", "--version"
  end
end
