# This file was generated by GoReleaser. DO NOT EDIT.
cask "close-wiki" do
  version "0.9.2"

  on_macos do
    on_intel do
      sha256 "8a10d3d613e6715c32de9fd03dd2c0bf1c6c475021e983a6bd82b082658c6175"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d926701d1427b2222e84d0f61425a522b0d36a7f0c872baec1d7b5104099e3b0"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b51dc76b0de44bcf445af04d17ca184d489dc7d6cbdb7560698819f7dc9058cc"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4143156915a7ec7e839aa5a676b9b67a438bd67f56892d90e10407f3d5df746"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_linux_arm64.tar.gz"
    end
  end

  name "close-wiki"
  desc "Agentic repo-to-wiki — scan any codebase into a structured knowledge base"
  homepage "https://github.com/unrealandychan/close-wiki"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "close-wiki"

  # No zap stanza required

end
