# This file was generated by GoReleaser. DO NOT EDIT.
cask "close-wiki" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "7e01fc47390251bcad5266eec17f192b84a96f4df598a5f4074a4a2be91fec79"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bed562123460989cbe42050ef47d6e5301c19938b09a0a04bf86e926f9758eb8"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eab4fe8109d20da77706e1efbe802f9cbfd60565f90e6c7f9d7b792fba835a30"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3df7ec8e6cd5740c1d697730e2ec1209b6848587a2b9862b5868dd3a7fd219b"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_linux_arm64.tar.gz"
    end
  end

  name "close-wiki"
  desc "Agentic repo-to-wiki — scan any codebase into a structured knowledge base"
  homepage "https://github.com/unrealandychan/close-wiki"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "close-wiki"

  # No zap stanza required

end
