# This file was generated by GoReleaser. DO NOT EDIT.
cask "close-wiki" do
  version "0.9.3"

  on_macos do
    on_intel do
      sha256 "958c8ebfc0c4ff80fbff59e7ed8396aebf320c859dec70ad803781148ed7580a"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "01522d0f45dfdf196b6dc0f12d7f0d173ecd2ceaeb6cde7a2addf1ac5f76b164"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "37dd2aecfc5779e71b7a8d6b70ffd7ad8119ca6e16868928cf76fd09cf5af1a0"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6a31d73f1cc11d28423ae23715fbbb923c9f2d6cfe08a03c721c3768664cf363"
      url "https://github.com/unrealandychan/close-wiki-releases/releases/download/v#{version}/close-wiki_linux_arm64.tar.gz"
    end
  end

  name "close-wiki"
  desc "Agentic repo-to-wiki — scan any codebase into a structured knowledge base"
  homepage "https://github.com/unrealandychan/close-wiki"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "close-wiki"

  # No zap stanza required

end
