# This file was generated by GoReleaser. DO NOT EDIT.
cask "rekipedia" do
  version "0.9.11"

  on_macos do
    on_intel do
      sha256 "4dc495437ffa136622a8dc533780eec0c00d1648d836c8ce2c9455e3118d4c46"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c36256bc2b4b29d188df0f7c042f212c5978010fbcbe8557c14882521e066d33"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "abe40ee5e9ddded788703d4a763e1844d0ac642aab09811407a84202626db841"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4adce852930caaeff9ffced113f0e82c2bea31be15b96e750e46ce1c0e041ca6"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_linux_arm64.tar.gz"
    end
  end

  name "rekipedia"
  desc "Agentic repo-to-wiki — scan any codebase into a structured knowledge base"
  homepage "https://github.com/unrealandychan/rekipedia"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reki"

  # No zap stanza required

end
