# This file was generated by GoReleaser. DO NOT EDIT.
cask "rekipedia" do
  version "0.9.9"

  on_macos do
    on_intel do
      sha256 "3d0836b054744285bac65cba84bd42a86821419c585dd58c71379593183ab412"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "865c531e415f3b69bd5b5700026542ae0b39d62b91ffdc0e060576ceda0759ae"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c9e5ff98af40a62443fc931e7832633b7427a879073405534fb6fcb93230ee1b"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6bb264ada32fcc72480ef803e7b1e3d25d10c1ee9164d6ec20bacc96cdcb69c8"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_linux_arm64.tar.gz"
    end
  end

  name "rekipedia"
  desc "Agentic repo-to-wiki — scan any codebase into a structured knowledge base"
  homepage "https://github.com/unrealandychan/rekipedia"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reki"

  # No zap stanza required

end
