# This file was generated by GoReleaser. DO NOT EDIT.
cask "rekipedia" do
  version "0.9.8"

  on_macos do
    on_intel do
      sha256 "d2a307b5b763f13a6f9c3c8dfcdb4c2ac9d285aff4b40873c07e8555b2d3cf4f"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "de77cc27c788bca75172542d24d7ce3bc10a91341ce04182e3234cf777757c62"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a00ba1e4a4b42cdcde1a063aa12e784aa385ffecae69c0b10c95363c17992bc5"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2129e0d79264217f339334349539feaad4435436dcdd98f64a3b64f0b54f3fde"
      url "https://github.com/unrealandychan/rekipedia-releases/releases/download/v#{version}/rekipedia_linux_arm64.tar.gz"
    end
  end

  name "rekipedia"
  desc "Agentic repo-to-wiki — scan any codebase into a structured knowledge base"
  homepage "https://github.com/unrealandychan/rekipedia"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reki"

  # No zap stanza required

end
