# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloseWiki < Formula
  desc "Your AI tech lead — scan any repo into a searchable knowledge store"
  homepage "https://github.com/unrealandychan/close-wiki"
  version "0.8.4-go"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.8.4-go/close-wiki_0.8.4-go_darwin_amd64.tar.gz"
      sha256 "a32671f8404b9e288e5de7b0e9672105c9e4166da6124342262f4c1864233e04"

      define_method(:install) do
        bin.install "close-wiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.8.4-go/close-wiki_0.8.4-go_darwin_arm64.tar.gz"
      sha256 "9ec2c4622d68c0ee58af3f2f196081fbfeba0f75cfc3c2fb4cfad57bd949ccda"

      define_method(:install) do
        bin.install "close-wiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.8.4-go/close-wiki_0.8.4-go_linux_amd64.tar.gz"
      sha256 "2466d2070f8261c9ad7c85c0289cb16c9da9b86580ed7c898118a68c575d3752"
      define_method(:install) do
        bin.install "close-wiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.8.4-go/close-wiki_0.8.4-go_linux_arm64.tar.gz"
      sha256 "2321627483858622a6e28d8b3017e5dbb3fd4f8ef5e4aad7a94bd8b17564a905"
      define_method(:install) do
        bin.install "close-wiki"
      end
    end
  end

  test do
    system "#{bin}/close-wiki --version"
  end
end
