# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloseWiki < Formula
  desc "Your AI tech lead — scan any repo into a searchable knowledge store"
  homepage "https://github.com/unrealandychan/close-wiki"
  version "0.8.4-go"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.8.4-go/close-wiki_0.8.4-go_darwin_amd64.tar.gz"
      sha256 "94b643d77d83d249641d12961f69217c5f19e49aad4e5e6e6122c53e01a974d7"

      define_method(:install) do
        bin.install "close-wiki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.8.4-go/close-wiki_0.8.4-go_darwin_arm64.tar.gz"
      sha256 "647544e235cd820d5eb5550283dc422c610fcf594fed963bd7713f7790db35ed"

      define_method(:install) do
        bin.install "close-wiki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.8.4-go/close-wiki_0.8.4-go_linux_amd64.tar.gz"
      sha256 "4a24c7f8cdab51e3a6bc81f3f823037f09a0178d558c26195e5e3370a12a37e5"
      define_method(:install) do
        bin.install "close-wiki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unrealandychan/close-wiki/releases/download/v0.8.4-go/close-wiki_0.8.4-go_linux_arm64.tar.gz"
      sha256 "d24bee6d92b5de45cadc21bab13aea2d00c9281aec77dee9d80c758747080a37"
      define_method(:install) do
        bin.install "close-wiki"
      end
    end
  end

  test do
    system "#{bin}/close-wiki --version"
  end
end
